-- AlterTable
ALTER TABLE `pedido` ADD COLUMN `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    ADD COLUMN `status` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `total` INTEGER NOT NULL DEFAULT 0;
